services:
  redis:
    image: "redis:7.4.1-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  postgres:
    image: "postgres:17.1-alpine3.19"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  task:
    image: "task-management:1"
    ports:
      - "8000:8000"
    environment:
      - "PORT=8000"
      - "DATABASE_URL=postgres://admin:password@postgres:5432/tasks"

volumes:
  redis-data:
  postgres-data:
